### DISCUSSION TITLE
What is the best way to add eslint-plugin-qunit?

### DISCUSSION THREAD

**Discussion by tylervz** [oxsecurity/megalinter#2391] [Q&A] [answered]
I got MegaLinter to use `eslint-plugin-qunit` which has rules for linting QUnit tests, but I'm not sure the way I went about it is recommend or considered best practice. Can someone let me know what the best way to do so is?
I know there are specific ESLint plugins already installed on the mega-linter Docker image:

https://github.com/oxsecurity/megalinter/blob/main/docs/descriptors/javascript_eslint.md#installation-on-mega-linter-docker-image

**Describe the solution you'd like**
I would like to have MegaLinter use [eslint-plugin-qunit](https://github.com/platinumazure/eslint-plugin-qunit) which has rules for linting [QUnit tests](https://qunitjs.com/), or add a configurtion variable `JAVASCRIPT_ES_ADDITIONAL_PLUGINS` so users can specify additional ESLint plugins to be installed before ESLint runs i.e. `["eslint-plugin-qunit@latest", "eslint-plugin-jquery"]`, or update the documentation with a GitHub Actions example of how to install additional ESLint plugins (I could take on this task, if in fact my method of installing additional ESLint plugins is recommended).

**Describe alternatives you've considered**

The relevant part of my `.eslintrc.yml` file (which is in the root of my repository) is:
```yaml
###########
# Plugins #
###########
plugins:
  - "@typescript-eslint"

#########
# Rules #
#########
extends: ["eslint:recommended", "plugin:qunit/recommended"]
rules:
  array-callback-return: "error"
```

I was able to use `eslint-plugin-qunit` by adding it as a dev dependency in my `package.json` and running `npm install` before the MegaLinter action.

```yaml
jobs:
  build:
    name: MegaLinter
    runs-on: ubuntu-latest
    steps:
      # Git Checkout
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      # Install the npm dependencies
      - name: Install packages for Node
        run: npm install

      # MegaLinter
      - name: MegaLinter
        id: ml
        # You can override MegaLinter flavor used to have faster performances
        # More info at https://oxsecurity.github.io/megalinter/flavors/
        uses: oxsecurity/megalinter@v6
        env:
          # All available variables are described in documentation
          # https://oxsecurity.github.io/megalinter/configuration/
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

This was after I had first tried adding the following to `.mega-linter.yml`:
```yaml
JAVASCRIPT_ES_PRE_COMMANDS:
  - command: "npm install eslint-plugin-qunit@latest --save-dev"
    cwd: "workspace" # Will be run at the root of the workspace (usually your repository root)
  - command: "npm list --depth=0"
    cwd: "workspace"
```
And then the run failed because the `npm install` command ran in `/node-deps` rather than `/github/workspace`:

```text
- Using [eslint v8.33.0] https://megalinter.io/6.19.0/descriptors/javascript_eslint
  - MegaLinter key: [JAVASCRIPT_ES]
  - Rules config: identified by [eslint]
  - Number of files analyzed: [7]
  [Pre][JAVASCRIPT_ES] run: [cd /node-deps && npm install eslint-plugin-qunit@latest --save-dev] in cwd [/github/workspace]
  [Pre][JAVASCRIPT_ES] 
  added 3 packages, removed 2 packages, changed 2 packages, and audited 2324 packages in 10s
  
  227 packages are looking for funding
    run `npm fund` for details
  
  15 vulnerabilities (2 moderate, 12 high, 1 critical)
  
  To address issues that do not require attention, run:
    npm audit fix
  
  To address all issues (including breaking changes), run:
    npm audit fix --force
  
  Run `npm audit` for details.
  
  [Pre][JAVASCRIPT_ES] run: [npm list --depth=0] in cwd [/github/workspace]
  [Pre][JAVASCRIPT_ES] com.hypercision.attproto@5.2.4 /github/workspace
  └── (empty)
  
  
  --Error detail:
  
  Oops! Something went wrong! :(
  
  ESLint: 8.33.0
  
  ESLint couldn't find the plugin "eslint-plugin-qunit".
  
  (The package "eslint-plugin-qunit" was not found when loaded as a Node module from the directory "/github/workspace".)
```
