### DISCUSSION TITLE
How to configure mega-linter to only lint a certain folder in monorepo?

### DISCUSSION THREAD

**Discussion by tomkortjak** [oxsecurity/megalinter#2906] [Q&A]
Discussion continued in: https://github.com/oxsecurity/megalinter/issues/2912 

my configuration is as follows:
```
FAIL_IF_MISSING_LINTER_IN_FLAVOR: true
APPLY_FIXES: all
ENABLE_LINTERS:
  - JAVASCRIPT_ES
  - TYPESCRIPT_ES
  - TSX_ESLINT
  - JSX_ESLINT
#DISABLE:
#  - COPYPASTE
#  - SPELL 
SHOW_ELAPSED_TIME: true
PRINT_ALPACA: false
FILEIO_REPORTER: false
# DISABLE_ERRORS: true
FLAVOR_SUGGESTIONS: true 
VALIDATE_ALL_CODEBASE: false 
LOG_LEVEL: DEBUG
LINTER_RULES_PATH: .
```

workflow job: 
```
- name: MegaLinter
        id: ml
        uses: oxsecurity/megalinter/flavors/javascript@v7
        env: 
          DEFAULT_WORKSPACE: app/react
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MEGALINTER_CONFIG: .github/.mega-linter.yml
```

The project contains a react project in app/react. I basically want to linter to only check for modified files in this directory. When scanning for modified files a get a correct list from the git diff, but the filtered list only includes the .gitignore:
```
Listing updated files in [/github/workspace] using git diff.
  Failed checking if running in CYGWIN due to: FileNotFoundError(2, 'No such file or directory')
  Popen(['git', 'fetch', 'origin', 'HEAD:refs/remotes/origin/HEAD'], cwd=/github/workspace, universal_newlines=False, shell=None, istream=None)
  Popen(['git', 'diff', '--name-only', 'origin/HEAD'], cwd=/github/workspace, universal_newlines=False, shell=None, istream=None)
  Modified files:
  .github/.mega-linter.yml
  .github/workflows/react_tests.yml
  .gitignore
  app/react/.cspell.json
  app/react/.eslintrc.js
  app/react/.jscpd.json
  app/react/npm-shrinkwrap.json
  app/react/src/pages/administration/inbox/InboxEditForm.tsx
  All found files before filtering:
  - .gitignore
  - File extensions: .js, .jsx, .ts, .tsx, .vue
```

I suspect it's because of line 761 in MegaLinter.py
`  if os.path.isfile(self.workspace + os.path.sep + diff_line): `

How should I configure the workflow so that it recognises files like "app/react/src/pages/administration/inbox/InboxEditForm.tsx" ?

Additional question, currently we are setting DEFAULT_WORKSPACE: app/react. Otherwise it can't find the .eslintrc.json file. Is there also another to configure the path to this lint file? I wasn't able to find any in the docs.
