### DISCUSSION TITLE
All Poetry dependencies missing

### DISCUSSION THREAD

**Discussion by andrewvaughan** [oxsecurity/megalinter#3291] [Q&A] [answered]
I've been using Megalinter for a while, but it's been a minute since I've touched a Python project with it, and...

![...I feel like I'm taking crazy pills!](https://media1.tenor.com/m/JeyPTQ9GX7gAAAAC/i-feel-like-im-taking-crazy-pills-will-ferrell.gif)

I don't recall ever have an issue using Poetry and Megalinter before - my understanding was that my `.venv` folder would load into the Docker container. That said, using the `python` flavor, it seems none of my Python linters can find my loaded dependencies:

```text
[MegaLinter/MegaLinter]   ❓  ::group::❌ Linted [PYTHON] files with [pyright]: Found 5 error(s) - (9.22s) (expand for details)
| - Using [pyright v1.1.339] https://megalinter.io/7.7.0/descriptors/python_pyright
| - MegaLinter key: [PYTHON_PYRIGHT]
| - Rules config: identified by [pyright]
| - Number of files analyzed: [8]
| --Error detail:
| 
| added 1 package, and audited 2 packages in 4s
| 
| found 0 vulnerabilities
| /Users/andrew/Repositories/Personal/tuna-piano/TunaPiano/Audio/DeviceManager.py
|   /Users/andrew/Repositories/Personal/tuna-piano/TunaPiano/Audio/DeviceManager.py:24:8 - error: Import "sounddevice" could not be resolved (reportMissingImports)
| /Users/andrew/Repositories/Personal/tuna-piano/TunaPiano/__main__.py
|   /Users/andrew/Repositories/Personal/tuna-piano/TunaPiano/__main__.py:50:8 - error: Import "click" could not be resolved (reportMissingImports)
|   /Users/andrew/Repositories/Personal/tuna-piano/TunaPiano/__main__.py:51:8 - error: Import "inquirer" could not be resolved (reportMissingImports)
|   /Users/andrew/Repositories/Personal/tuna-piano/TunaPiano/__main__.py:60:71 - error: Cannot access member "getInputDevices" for type "object"
|     Member "getInputDevices" is unknown (reportGeneralTypeIssues)
|   /Users/andrew/Repositories/Personal/tuna-piano/TunaPiano/__main__.py:62:45 - error: Cannot access member "getDefaultInputDevice" for type "object"
|     Member "getDefaultInputDevice" is unknown (reportGeneralTypeIssues)
| 5 errors, 0 warnings, 0 informations 
| WARNING: there is a new pyright version available (v1.1.339 -> v1.1.347).
| Please install the new version or set PYRIGHT_PYTHON_FORCE_VERSION to `latest`

//...

[MegaLinter/MegaLinter]   ❓  ::group::❌ Linted [PYTHON] files with [pylint]: Found 3 error(s) - (1.85s) (expand for details)
| - Using [pylint v3.0.2] https://megalinter.io/7.7.0/descriptors/python_pylint
| - MegaLinter key: [PYTHON_PYLINT]
| - Rules config: [.pylintrc]
| - Number of files analyzed: [8]
| --Error detail:
| pylint: Command line or configuration file:1: UserWarning: 'Exception' is not a proper value for the 'overgeneral-exceptions' option. Use fully qualified name (maybe 'builtins.Exception' ?) instead. This will cease to be checked at runtime in 3.1.0.
| ************* Module TunaPiano.Audio.DeviceManager
| TunaPiano/Audio/DeviceManager.py:24:0: E0401: Unable to import 'sounddevice' (import-error)
| ************* Module TunaPiano.__main__
| TunaPiano/__main__.py:50:0: E0401: Unable to import 'click' (import-error)
| TunaPiano/__main__.py:51:0: E0401: Unable to import 'inquirer' (import-error)
```

I've tried adding a pre-command to do a simple Python install (although this seems duplicative):

```yml
PRE_COMMANDS:
  - command: poetry install --no-root
    cwd: workspace
```

I've tried installing dependencies into each of the linters virtual environments (which hurt my soul):

```yml
PRE_COMMANDS:
  - command: poetry install --no-root
    venv: pyright
  - command: poetry install --no-root
    venv: pylint
```

I've even tried calling `act` locally within Poetry to see if it made a difference:

```sh
poetry run \
  act \
    --rm \
    --container-architecture "linux/amd64" \
    pull_request
```

I don't recall ever having to do any of these things, which is making me think I'm missing something simple. Can anyone please point me to what that is? Thanks!

**Comment by andrewvaughan** [comment]
Poking through the [flavor `Dockerfile`](https://github.com/oxsecurity/megalinter/blob/main/flavors/python/Dockerfile#L119-L140), I see that megalinter creates a `venv` for each and every Python linter. Does this mean I have to both install my package manager and all dependencies (or something similar) to every linter that needs visibility into my dependencies?

```yaml
PRE_COMMAND:
  - command: python3 -m pip install poetry
    venv: pylint
    continue_if_failed: false

  - command: python3 -m poetry install --no-root
    venv: pylint
    continue_if_failed: false
```

This is _wildly_ inefficient, if so - taking up easily 10x the time and disk space required for linting - so I'm hoping someone can point me toward a more sane solution wherein I can point linters toward a shared virtual environment. I'm not sure I understand the rationale for splitting out so many virtual environments in the first place.

> (Note, this still fails, because the `install` command can't find my `pyproject.toml` file... so this isn't working, but seems like it's the intended way Megalinter wants you to manage project dependencies for each of these linters?).

Most comments I see online are "just disable the `import` checking" which... really defeats the purpose of having a linter.

**Comment by andrewvaughan** [comment]
I figured out an interim solution and, I'll be honest, I hate it. It does the following:

1. Installs `poetry` once and exports a `requirements.txt` file from the Poetry configuration to the `/venvs` directory
2. Manually installs all project dependencies into each linter's virtual environment that needs it - yep, duplicating installs for each one... oof.

```yaml
PRE_COMMANDS:
  # Export the Poetry configuration to a `requirements.txt` file that each of the virtual environments can use
  - command: python3 -m pip install poetry
    cwd: root
    continue_if_failed: false

  - command: poetry export --without-hashes -f requirements.txt -o /venvs/requirements.txt
    cwd: workspace
    continue_if_failed: false

  # Install dependencies for `pylint`
  - command: python3 -m pip install --no-cache-dir -r /venvs/requirements.txt
    venv: pylint
    continue_if_failed: false

  # Install dependencies for `pyright`
  - command: python3 -m pip install --no-cache-dir -r /venvs/requirements.txt
    venv: pyright
    continue_if_failed: false
```

I'm hoping @nvuillam or crew can impart some wisdom on me as to how this might be better managed. I really hate duplicating dependency installations on each and every test because there are dozens of virtual environments created...
