### ISSUE TITLE
post-css module installation

### ISSUE THREAD

**Issue by RyanMulready** [oxsecurity/megalinter#1258]
I've been trying to get https://github.com/ota-meshi/stylelint-config-recommended-vue working with Megalinter's stylelint configuration. It has a dependency of `postcss-html` which needs to be installed. Based on https://megalinter.github.io/latest/configuration/#pre-commands it seems the following should work but it does not. I've tried a variation of installing different packages to no avail.

```yml
PRE_COMMANDS:
  - continue_if_failed: false
    command: npm install postcss-html stylelint-config-recommended-vue
    cwd: workspace
```

Error:

```bash
Error: Cannot resolve custom syntax module "postcss-html". Check that module "postcss-html" is available and spelled correctly.

Caused by: Error: Cannot find module 'postcss-html'
Require stack:
- /node_modules/stylelint/lib/getPostcssResult.js
- /node_modules/stylelint/lib/createStylelint.js
- /node_modules/stylelint/lib/resolveConfig.js
- /node_modules/stylelint/lib/printConfig.js
- /node_modules/stylelint/lib/cli.js
- /node_modules/stylelint/bin/stylelint.js
    at getCustomSyntax (/node_modules/stylelint/lib/getPostcssResult.js:105:11)
    at getPostcssResult (/node_modules/stylelint/lib/getPostcssResult.js:41:5)
    at lintSource (/node_modules/stylelint/lib/lintSource.js:79:20)
    at async /node_modules/stylelint/lib/standalone.js:223:27
    at async Promise.all (index 13)
    at async standalone (/node_modules/stylelint/lib/standalone.js:262:22)
```

**Comment by nvuillam** [comment]
Please can you try the following config ?

```yaml
PRE_COMMANDS:
  - continue_if_failed: false
    command: npm install postcss-html stylelint-config-recommended-vue
    cwd: root
```
