### ISSUE TITLE
`EXTENDS` in `.mega-linter.yml`: Properties from extended file override properties in extending file

### ISSUE THREAD

**Issue by lars-reimann** [oxsecurity/megalinter#1516]
**Describe the bug**
To simplify the configuration of MegaLinter across multiple repos I want to have one [base config in my `.github` repo](https://github.com/lars-reimann/.github/blob/2a05588583f77cc571d4b7a5dae0b0b3f0fe6b8e/.mega-linter.yml) and then have a short configuration in each other repo that adds properties or overrides the ones from the base config. For example, in one repository I want to override the `FILTER_REGEX_EXCLUDE` property:

```yml
EXTENDS: https://raw.githubusercontent.com/lars-reimann/.github/main/.mega-linter.yml

# Config
FILTER_REGEX_EXCLUDE: (\.github/workflows/|someOtherFolder/)
```

However, this does not seem to work as expected: The `FILTER_REGEX_EXCLUDE` property from the extended config overrides the property defined here rather than the other way around. This means the base config can only contain properties that I know I'll never want to override.

**To Reproduce**

1. Create a base config.
2. Create another config that extends the base config and overrides one of its properties.
3. Observe the behavior of the linter.

**Expected behavior**
The property in the extending file should have precedence.

**Additional context**
At first glance this seems to cause this behavior: https://github.com/megalinter/megalinter/blob/100a4d937a48c79e0eb5de8325d4d2b22601d861/megalinter/config.py#L82
