### ISSUE TITLE
TERRAFORM_CHECKOV_ARGUMENTS not working 

### ISSUE THREAD

**Issue by Divyenth-K** [oxsecurity/megalinter#1539]
I Am trying to skip few checks and files in checkov but TERRAFORM_CHECKOV_ARGUMENTS variable in the megalinter action does not seem to work 

``` yaml
my workflow file : 
    steps:
      - uses: actions/checkout@v3
        name: Checkout source code
      - name: MegaLinter-tf
        id: ml
        uses: megalinter/megalinter@v5.14.0
        env:
          VALIDATE_ALL_CODEBASE: true
          PRINT_ALPACA: false
          GITHUB_TOKEN: ${{ secrets.SAML_GITHUB_TOKEN }}
          ENABLE_LINTERS: TERRAFORM_CHECKOV,TERRAFORM_TFLINT
          PARALLEL: true
          GITHUB_COMMENT_REPORTER: true 
          TERRAFORM_CHECKOV_ARGUMENTS: --skip-check CKV_SECRET_6
```
