### ISSUE TITLE
Specify python version

### ISSUE THREAD

**Issue by SoumayaMauthoorMOJ** [oxsecurity/megalinter#1637]
I can specify which python version(s) to use when linting my code with custom Github action:

```
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
```

How can I specify python version(s) with the mega-linter Github action?
