### ISSUE TITLE
Different results while running flavor in container vs. running flavor with CLI 

### ISSUE THREAD

**Issue by shiranr** [oxsecurity/megalinter#1791]
**Describe the bug**
I might be doing something wrong but when using the following command:
docker run  -v PROJECT_PATH:/tmp/lint oxsecurity/megalinter-documentation:v6
vs. Using this command:
npx mega-linter-runner --flavor documentation
over the same repository and branch, I get different results.

**To Reproduce**
1. The config file .mega-linter.yml:
```yaml
---
DEFAULT_BRANCH: main
VALIDATE_ALL_CODEBASE: false
SPELL_CSPELL_FILTER_REGEX_INCLUDE: (.*\.md)
FILTER_REGEX_INCLUDE: (.*\.yml|.*\.yaml|.*\.md|.*\.json)

ENABLE_LINTERS:
  - SPELL_CSPELL
  - YAML_YAMLLINT
  - REPOSITORY_SECRETLINT
```
2. file.py:
```python
def print_hello():
    # THIS IS A SECRET: 'mongodb://myDBReader:Password@mongodb0.example.com:27017/?authSource=admin'
    print("Hello") 
```
3. Both files should be fully committed into main.
4. Create new branch.
5. Run:
npx mega-linter-runner --flavor documentation
The result will be:
```
::set-output name=has_updated_sources::0
✅ Successfully linted all files without errors
```
6. Run:
docker run  -v PROJECT_PATH:/tmp/lint oxsecurity/megalinter-documentation:v6
The result will be:
```
+----SUMMARY----+------------+---------+-------+-------+--------+--------------+
| Descriptor    | Linter     | Mode    | Files | Fixed | Errors | Elapsed time |
+---------------+------------+---------+-------+-------+--------+--------------+
| ❌ REPOSITORY | secretlint | project |   n/a |       |      1 |        0.93s |
+---------------+------------+---------+-------+-------+--------+--------------+

[Updated Sources Reporter] No source file has been formatted or fixed
::set-output name=has_updated_sources::0

```
**Expected behavior**
I would expect the MegaLinter have the same behavior for flavor document.  
The right one here IMO is 4 and the MegaLinter should finish successfully since the flag: VALIDATE_ALL_CODEBASE: false
and FILTER_REGEX_INCLUDE: (.*\.yml|.*\.yaml|.*\.md|.*\.json) so the .py file should not even be considered.
