### ISSUE TITLE
[v6.1] Add support for PHP 8.1

### ISSUE THREAD

**Issue by llaville** [oxsecurity/megalinter#2086]
**Is your feature request related to a problem? Please describe.**
Actually, if you want to use [PHPStan](https://oxsecurity.github.io/megalinter/6.13.0/descriptors/php_phpstan/) linter on a PHP project that required at least PHP 8.1, you got an error as follow 

![phpstan-php8](https://user-images.githubusercontent.com/364342/202657635-12b1d664-5925-46fc-bfcd-b539ea50b420.png)

Chunk of **.mega-linter.yml**
```yaml
ENABLE:
    - ACTION
    - EDITORCONFIG
    - JSON
    - MARKDOWN
    - PHP
    - YAML
DISABLE_LINTERS:
    - JSON_JSONLINT
    - JSON_V8R
    - MARKDOWN_MARKDOWN_TABLE_FORMATTER
    - MARKDOWN_MARKDOWN_LINK_CHECK
    - PHP_BUILTIN
    - PHP_PSALM
    - YAML_V8R
PHP_PHPSTAN_CLI_LINT_MODE: project
PHP_PHPLINT_CLI_LINT_MODE: project
PHP_PHPCS_CLI_LINT_MODE: project
PHP_PHPSTAN_PRE_COMMANDS:
    - command: "update-alternatives --set php /usr/bin/php8"
      cwd: root

```

**Describe the solution you'd like**
Related to discussion started from https://github.com/oxsecurity/megalinter/pull/2039#issuecomment-1302997006 about drop support of PHP 7, we should consider to add support both PHP 8.0 and 8.1 (and perharps later 8.2.0 will come shortly now in stable status) 

The reason came from PHP descriptors used in MegaLinter v6.1 : https://oxsecurity.github.io/megalinter/latest/descriptors/php/

Especially https://pkgs.alpinelinux.org/packages?branch=edge&name=php8

PHP 8.1 is only supported in Alpine Linux Package since v3.16; see 
- https://pkgs.alpinelinux.org/packages?name=php81&branch=v3.16&repo=&arch=&maintainer=
- https://pkgs.alpinelinux.org/packages?name=php81&branch=edge&repo=&arch=&maintainer=

**Describe alternatives you've considered**
Disable temporay PHPStan linter for project that requires PHP 8.1 or greater
