### ISSUE TITLE
Documentation Improvement: Adding Detailed Steps for Implementing a Simple Linter and Warnings for Actions to Avoid

### ISSUE THREAD

**Issue by ThomasSanson** [oxsecurity/megalinter#2399]
I would like to propose an improvement to the existing documentation by adding detailed steps for implementing a simple linter and important warnings for actions to avoid.

I suggest adding detailed steps for implementing an existing simple linter, explaining each step in detail so that users can easily understand and follow the instructions. Additionally, I propose implementing clear warnings for actions to avoid, such as touching generated files created by the linter.

I am willing to contribute to writing these instructions and assisting with the implementation of these warnings.

Thank you in advance for considering my proposal.

**Comment by bdovaz** [comment]
Having this reference: https://megalinter.io/beta/contributing/#add-a-new-linter

Points that come to mind:
* Clearly indicate where to create the descriptor.
* Explain the automatic testing system that generates a class for each linter with several methods (success, fail, get help, get version, sarif, ...):
  * Skips certain tests based on certain fields in the linter or certain conditions.
  * The magic of those "_good", "_bad" and "_fix" in folder or filenames
  * Indicate that input files must be created for each test that requires them (success, fail, fix).

I personally added these 2 blocks that I understand that they make development much easier and at the time I did not have this information:

https://megalinter.io/beta/contributing/#execute-the-tests-locally-visual-studio-code

https://megalinter.io/beta/contributing/#execute-linter-tests-inside-the-container

It helps you not to depend so much on CI and those eternal executions that frustrate a lot.

If you see something that can be improved, you can say it.

**Comment by nvuillam** [comment]
Maybe we could split the contributing into several pages ?
It would maybe look less messy ^^

**Comment by ThomasSanson** [comment]
test.sh
```bash
#!/bin/bash

name="${1:-kubernetes_helm}"
image_name="oxsecurity/megalinter-only-${name}"

# Build and tag the Docker image
docker buildx build -f "linters/${name}/Dockerfile" . --tag "${image_name}"

# Use the case substitution to get the linter name in uppercase
docker run \
  -e TEST_CASE_RUN=true \
  -e OUTPUT_DETAIL=detailed \
  -e TEST_KEYWORDS="${name^^}" \
  -e MEGALINTER_VOLUME_ROOT="." \
  -v "/var/run/docker.sock:/var/run/docker.sock:rw" \
  -v "$(pwd)":/tmp/lint \
  "${image_name}"
  ```

**Comment by ThomasSanson** [comment]
note :

if you don't want to mess with other kubernetes linters, just put your test files in a kubernetes_helm folder, and add test_folder: kubernetes_helm in the helm linter descriptor

**Comment by ThomasSanson** [comment]
run_linter_locally.sh

```bash
#!/bin/bash

# Check that the user provided a linter name, ex : kubernetes_helm
if [ -z "$1" ]; then
  echo "$(tput setaf 1) Error: Please provide the name of the linter to run as the first argument like kubernetes_helm $(tput sgr0)"
  exit 1
fi

# Specify the name of the linter to run
name="$1"

# Specify the name of the Docker image to build
image_name="oxsecurity/megalinter-only-${name}"

# Build and tag the Docker image
docker buildx build -f "linters/${name}/Dockerfile" . --tag "${image_name}" || {
  echo "$(tput setaf 1) Error: Failed to build the Docker image. $(tput sgr0)"
  exit 1
}

# Use the case substitution to get the linter name in uppercase
docker run \
  -e TEST_CASE_RUN=true \
  -e OUTPUT_DETAIL=detailed \
  -e TEST_KEYWORDS="${name^^}1" \
  -e MEGALINTER_VOLUME_ROOT="." \
  -v "/var/run/docker.sock:/var/run/docker.sock:rw" \
  -v "$(pwd)":/tmp/lint \
  -v "$(pwd)/reports:/tmp/reports" \
  "${image_name}" ||
  {
    echo "$(tput setaf 1) Error: Failed to run the linter. $(tput sgr0)"
    exit 1
  }
```

**Comment by ThomasSanson** [comment]
- Add linter desciptor
```yaml
  # HELM LINT
  - linter_name: helm
    name: KUBERNETES_HELM
    linter_repo: https://github.com/helm/helm
    linter_url: https://helm.sh/docs/helm/helm_lint/
    linter_version_cache: "v3.11.1"
    files_sub_directory: "" 
    test_folder: kubernetes_helm
    cli_lint_mode: project
    cli_help_arg_name: -h
    cli_lint_extra_args:
      - "lint"
    linter_banner_image_url: https://user-images.githubusercontent.com/19731161/142411871-f695e40c-bfa8-43ca-97c0-94c256749732.png
    linter_text: |
      `helm lint` examine a chart for possible issues.
    examples:
      - helm lint .
      - helm lint --with-subcharts .
    install:
      apk:
        - helm
```

- add tests 
  - create folder `kubernetes_helm`
    - create subfolder `good`
      - add your good file
    - create subfolder `bad`
      - add your bad file

- run ./build.sh to generate code
- run ./run_linter_locally.sh
