### ISSUE TITLE
Running with nektos/act, pylint not found

### ISSUE THREAD

**Issue by bpowell** [oxsecurity/megalinter#2410]
I'm trying to run megalinter with [act](https://github.com/nektos/act) and every time I try to use `pylint`, I keep getting the following error:
```
| Traceback (most recent call last):
|   File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 125, in worker
|     result = (True, func(*args, **kwds))
|   File "/usr/local/lib/python3.10/site-packages/megalinter-0.1-py3.10.egg/megalinter/MegaLinter.py", line 37, in run_linters
|     linter.run()
|   File "/usr/local/lib/python3.10/site-packages/megalinter-0.1-py3.10.egg/megalinter/Linter.py", line 667, in run
|     return_code, stdout = self.process_linter()
|   File "/usr/local/lib/python3.10/site-packages/megalinter-0.1-py3.10.egg/megalinter/Linter.py", line 804, in process_linter
|     return_code, return_output = self.execute_lint_command(command)
|   File "/usr/local/lib/python3.10/site-packages/megalinter-0.1-py3.10.egg/megalinter/Linter.py", line 846, in execute_lint_command
|     process = subprocess.run(
|   File "/usr/local/lib/python3.10/subprocess.py", line 501, in run
|     with Popen(*popenargs, **kwargs) as process:
|   File "/usr/local/lib/python3.10/subprocess.py", line 966, in __init__
|     self._execute_child(args, executable, preexec_fn, close_fds,
|   File "/usr/local/lib/python3.10/subprocess.py", line 1842, in _execute_child
|     raise child_exception_type(errno_num, err_msg, err_filename)
| FileNotFoundError: [Errno 2] No such file or directory: 'pylint'
| """
```

I'm currently using version `oxsecurity/megalinter:v6.19.0`.  The documentation says that all of the linters are installed into the container, but I'm not seeing `pylint` when running it via `act`. 

I'm using the following GitHub Action workflow locally:
```
name: MegaLinter
on:
  pull_request:

jobs:
  MegaLinter:
    name: Run Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: MegaLinter
        uses: oxsecurity/megalinter@v6
        env:
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
and then my `.megalinter.yml` contains:
```
ENABLE_LINTERS:
  - PYTHON_PYLINT
```

To run with `act`, I do `act -j MegaLinter pull_request`

Is there anything that I am missing? Thanks for any help!
