### ISSUE TITLE
Trivy started failing with: panic: assignment to entry in nil map

### ISSUE THREAD

**Issue by atodorov** [oxsecurity/megalinter#2526]
**Describe the bug**

I've rebased an open PR, https://github.com/gluwa/creditcoin/pull/899, to pick up on some cargo updates and I wanted to see if that would resolve issues previously reported by Trivy. This time however Trivy started failing. See full traceback at:

https://github.com/gluwa/creditcoin/actions/runs/4617103427/jobs/8162938177?pr=899

**Comment by nvuillam** [comment]
I don't see the PANIC in your log https://github.com/gluwa/creditcoin/actions/runs/4504152148/jobs/7928261090

Probably that trivy released new security issues (the database is updated before each trivy run) and that detects those issues in your code base.

You can either:
- Fix the issues(probably by upgrading dependencies)
- Add a .trivyignore file at the root of your repo to ignore some issues that you consider not relevant

In your case, the .trivyignore file would be something like :

```
CVE-2020-26235
CVE-2022-39393
CVE-2023-26489
CVE-2023-27477
DS026
```

**Comment by nvuillam** [comment]
Same with checkov issues

.checkov.yml at the repo root

```yaml
# You can see all available properties here: https://github.com/bridgecrewio/checkov#configuration-using-a-config-file
quiet: true
skip-check: 
  - CKV_DOCKER_2
  - CKV2_GHA_1
```

You can also [disable or make not blocking linters](https://megalinter.io/6.7.0/configuration/#activation-and-deactivation), but it is not recommended for security linters :)
