### ISSUE TITLE
Megalinter refuses to run Plugins 

### ISSUE THREAD

**Issue by muandane** [oxsecurity/megalinter#2530]
i've been having issues with loading custom Plugins in megalinter, tested multiple flavors

```yaml
mega-linter:
  environment: dev-aks
  stage: Test 🛠️
  image: oxsecurity/megalinter-terraform:v6.22.2
  script: ["true"] # if script: ["true"] does not work, you may try ->  script: [ "/bin/bash /entrypoint.sh" ]
  variables:
    DEFAULT_WORKSPACE: ${CI_PROJECT_DIR}
    PRINT_ALPACA: "false"
    GITLAB_ACCESS_TOKEN_MEGALINTER: ${TF_VAR_GITLAB_ACCESS_TOKEN}
    PLUGINS: file://${CI_PROJECT_DIR}/mega-linter-plugin-kubescape/kubernetes.megalinter-descriptor.yml
    EXTENDS: .mega-linter.yml
  artifacts:
    when: always
    paths:
      - megalinter-reports
    expire_in: 1 week
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      allow_failure: true
```

```sh
MegaLinter flavor [terraform] does not contain linters KUBERNETES_KUBESCAPE,MAKEFILE_CHECKMAKE.
As they are not available in this docker image, they will not be processed
To solve this problem, please either: 
- use default flavor oxsecurity/megalinter
- add ignored linters in DISABLE or DISABLE_LINTERS variables in your .mega-linter.yml config file located in your root directory
- ignore this message by setting config variable FLAVOR_SUGGESTIONS to false
```
