### ISSUE TITLE
jscpd creates `report` folder despite `REPORT_OUTPUT_FOLDER: none`

### ISSUE THREAD

**Issue by bittner** [oxsecurity/megalinter#2623]
**Describe the bug**

```gherkin
Given I want MegaLinter not to create any report folder
When I set `REPORT_OUTPUT_FOLDER: none` in `.mega-linter.yml`
And run MegaLinter (using one of its official Docker images)
Then MegaLinter make `jscpd` creates a `report` folder.
```

**To Reproduce**

```yaml
# FILE: .mega-linter.yml
---
ENABLE:
- COPYPASTE
- MARKDOWN
- REPOSITORY
- YAML
DISABLE_LINTERS:
- MARKDOWN_MARKDOWN_LINK_CHECK
- REPOSITORY_CHECKOV
- YAML_PRETTIER
FORMATTERS_DISABLE_ERRORS: false
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .markdownlint.yml
PRINT_ALPACA: false
REPORT_OUTPUT_FOLDER: none
```

```
docker run --rm -v $PWD:/tmp/lint oxsecurity/megalinter-documentation:beta
```

Results:

- A `report` folder is created containing jscpd report data.
- The OX Security ASCII art logo is displayed despite `PRINT_ALPACA: false` in `.mega-linter.yml`.

```console
$ tree report
report
└── html
    ├── index.html
    ├── js
    │   └── prism.js
    ├── jscpd-report.json
    └── styles
        ├── prism.css
        └── tailwind.css

3 directories, 5 files
```

**Expected behavior**

- No report folder (of any kind) should be created.
- The OX Security ASCII art logo should be suppressed.

**Additional context**
See https://github.com/oxsecurity/megalinter/issues/2108#issuecomment-1537142338 for related information.
