### ISSUE TITLE
devskim failure: detected dubious ownership in repository

### ISSUE THREAD

**Issue by ahmadnassri** [oxsecurity/megalinter#2849]
**Describe the bug**
devskim fails with message:

```
git config --global --add safe.directory /tmp/lint/.git
fatal: detected dubious ownership in repository at '/tmp/lint/.git'
To add an exception for this directory, call:
```

**To Reproduce**

see the following failed run: https://github.com/ahmadnassri/action-commit-lint/actions/runs/5696529161/job/15441765582

I also replicated this locally with `make lint` command on that repo

**Expected behavior**

should probably set `git config --global --add safe.directory *` before running `devskim`

**Screenshots**

![image](https://github.com/oxsecurity/megalinter/assets/183195/ceb59c41-31db-4c44-9543-d75431366bdc)

**Additional context**
N/A

**Comment by nvuillam** [comment]
DevSkim is usually very chatty, too much in my opinion (that's why I often disable it on my repos :D )

@ahmadnassri as DevSkim has been upgraded since (sorry for the delay, long vacations ^^), do you still have the issue ?

**Comment by nvuillam** [comment]
@ahmadnassri thanks a lot :)

**Comment by Adafede** [comment]
> DevSkim is usually very chatty, too much in my opinion (that's why I often disable it on my repos :D )
> 
> @ahmadnassri as DevSkim has been upgraded since (sorry for the delay, long vacations ^^), do you still have the issue ?

The issue is still present. See https://github.com/taxonomicallyinformedannotation/tima-r/actions/runs/5999230667/job/16268961882#step:4:226 for example

**Comment by nvuillam** [comment]
@Adafede @ahmadnassri what if you add the following PRE_COMMAND iny your `.mega-linter.yml` config file ?

```yaml
REPOSITORY_DEVSKIM_PRE_COMMANDS:
  - command:  git config --global --add safe.directory /github/workspace/.git
    cwd: "root"
```

**Comment by Adafede** [comment]
@nvuillam nope 😢 

https://github.com/taxonomicallyinformedannotation/tima-r/actions/runs/6000122133/job/16271575111#step:4:226

**Comment by nvuillam** [comment]
Maybe this one ? :/

```yaml
REPOSITORY_DEVSKIM_PRE_COMMANDS:
  - command:  git config --global --add safe.directory /github/workspace/.git
    cwd: "workspace"
```
