### ISSUE TITLE
CSharpier Requires `dotnet tool restore`

### ISSUE THREAD

**Issue by Kurt-von-Laven** [oxsecurity/megalinter#2868]
**Describe the bug**

Beginning in v7.0.0, CSharpier crashes if `dotnet tool restore` hasn't been run.

```
❌ Linted [CSHARP] files with [csharpier]: Found 1 error(s) - (0.62s)
--Error detail:
Run "dotnet tool restore" to make the "dotnet-csharpier" command available.
```

**To Reproduce**

1. Run the dotnet flavor of MegaLinter in a project with C# files but no pre-commands.

**Expected behavior**
CSharpier runs successfully.

**Additional context**
I am splitting this issue out from #2578, which includes the workaround that can be added to `.mega-linter.yaml`:

```yaml
CSHARP_CSHARPIER_PRE_COMMANDS:
  - command: dotnet tool restore
    continue_if_failed: false
    cwd: workspace
```
