### ISSUE TITLE
Pre-commit hook integration is broken

### ISSUE THREAD

**Issue by vorburger** [oxsecurity/megalinter#3061]
**Describe the bug**
It appears https://megalinter.io/latest/mega-linter-runner/#pre-commit-hook is broken?

**To Reproduce**

Add https://megalinter.io/latest/mega-linter-runner/#pre-commit-hook to https://github.com/www-learn-study/saraswati.learn.study/blob/main/.pre-commit-config.yaml, 

which uses `pre-commit==3.5.0` (see https://github.com/www-learn-study/saraswati.learn.study/blob/main/requirements.txt) 

run https://github.com/www-learn-study/saraswati.learn.study/blob/main/bin/pre-commit.sh

**Expected behavior**
It works.

**Actual behavior**

```sh
$ pre-commit run

Detect hardcoded secrets.........................................................Passed
fix end of files.................................................................Passed
trim trailing whitespace.........................................................Passed
Run MegaLinter (skipping linters that run in project mode).......................Failed
- hook id: megalinter-incremental
- exit code: 1

/home/vorburger/.npm/_npx/614e542633a698fb/node_modules/optionator/lib/index.js:316
          throw new Error("Value for '" + prop + "' of type '" + getOption(prop).type + "' required.");
                ^

Error: Value for 'container-name' of type 'String' required.
    at checkProp (/home/vorburger/.npm/_npx/614e542633a698fb/node_modules/optionator/lib/index.js:316:17)
    at Object.parse (/home/vorburger/.npm/_npx/614e542633a698fb/node_modules/optionator/lib/index.js:356:13)
    at MegaLinterRunnerCli.run (file:///home/vorburger/.npm/_npx/614e542633a698fb/node_modules/mega-linter-runner/lib/cli.js:8:39)
    at file:///home/vorburger/.npm/_npx/614e542633a698fb/node_modules/mega-linter-runner/lib/index.js:12:37
    at file:///home/vorburger/.npm/_npx/614e542633a698fb/node_modules/mega-linter-runner/lib/index.js:13:5
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Node.js v18.18.2
```

**Additional context**

Perhaps there is a way for the project to detect this earlier by somehow self testing this?

**Comment by Kurt-von-Laven** [comment]
Thank you for reporting this issue. As a workaround, I would suggest passing the `--container-name` as an argument (an `args` array) to the pre-commit hook. Pre-commit has the unfortunate restriction of requiring hooks to be pinned to a release, making self-testing surprisingly cumbersome. I am open to suggestions from the community about how to achieve this or PRs.

**Comment by nvuillam** [comment]
Couldn't we use a default container name if not sent in options ?

**Comment by Kurt-von-Laven** [comment]
Yes, that is a very easy fix.

**Comment by lewis-jackson-bots** [comment]
@nvuillam I don't think that the pre-commit hooks as defined can be customised due to the use of `args`. e.g. if I have this `pre-commit` config:

```
  - repo: https://github.com/oxsecurity/megalinter
    rev: v7.10.0 # Git tag specifying the hook, not mega-linter-runner, version
    hooks:
      - id: megalinter-incremental # Faster, less thorough
        stages:
          - commit
      - id: megalinter-full # Slower, more thorough
        stages:
          - push
        args:
          - --containername
          - terraform
```

The `args` will just be passed to `npx --` like `npx -- containername terraform` overriding the defaults on this repo.

Let me know if I'm not doing this correctly!

For now I've just defined a local job:

```
  - repo: local
    hooks:
      - id: megalinter-terraform
        name: megalinter-terraform
        language: system
        require_serial: true
        entry: npx --
        args:
          - mega-linter-runner
          - --containername
          - megalinter-terraform
          - --remove-container
          # - --fix
          # - --env
          # - "'APPLY_FIXES=all'"
          - --env
          - "'CLEAR_REPORT_FOLDER=true'"
          - --env
          - "'LOG_LEVEL=warning'"
```
