### ISSUE TITLE
[solved] Vale (prose linter) setup

### ISSUE THREAD

**Issue by wesley-dean-flexion** [oxsecurity/megalinter#3087]
I found that `SPELL_VALE` works well locally on projects where I'm already using it.  Cool.  However, I found that just dropping a `.vale.ini` file into a project tends to fail if the following conditions are true:

* there is no directory present as specified in the `StylesPath` directive of the `.vale.ini` file
* there is a styles directory, but it doesn't have the styles mentioned in the `.vale.ini`

For example:

```
E201 Invalid value [/path/to/repo/.vale.ini:9:45]:

   8  ##
   9* ## See: https://vale.sh/docs/topics/config/#stylespath
  10  StylesPath = styles
  11  

The path '/path/to/repo/styles' does not exist.
```

or:

```
E100 [loadStyles] Runtime error
style 'alex' does not exist on StylesPath
```

(examples included so they show up in searches)

So, to fix that, one could create a styles directory in one's repo, then install Vale locally and run `vale sync` to acquire the styles, then commit all of that to the repo.  That seems like an anti-pattern to me.

Therefore, I added the following to my `.mega-linter.yml` file:

```yaml
# make sure Vale is setup to run with the styles it needs
SPELL_VALE_PRE_COMMANDS:
  - command: mkdir -p "$(git rev-parse --show-toplevel)/$(sed -Ene 's/^[[:space:]]*StylesPath[[:space:]]*=[[:space:]]*([^#]*)/\1/Ip' < .vale.ini)"
    cwd: "workspace"
  - command: vale sync
    cwd: "workspace"
```

This will:
1. parse out the StylesPath line from the `.vale.ini` file, then run `mkdir -p` on it (the `-p` flag has the side effect of having `mkdir` not throw an error if the directory already exists)
2. run `vale sync` which downloads the styles articulated in the `.value.ini` file

I believe that this is a better approach than having the Vale container synchronize the styles content itself as it allows the user to opt-in by including the steps needed to "make it go" while not requiring the addition of an additional MegaLinter configuration option to allow the user to opt-out.
