### ISSUE TITLE
Add "apply fixes" support to clang-format

### ISSUE THREAD

**Issue by daltonv** [oxsecurity/megalinter#3137]
clang-format is currently in the beta release, but does not add support for applying fixes automatically yet. 

To support this its descriptors should need the following lines:
```yaml
cli_lint_fix_arg_name: "-i"
cli_lint_fix_remove_args:
      - "--Werror"
      - "--dry-run"
```
