### ISSUE TITLE
Can we use _extends from another repo in same org 

### ISSUE THREAD

**Issue by bheemvennapureddy** [oxsecurity/megalinter#3400]
https://github.com/probot/octokit-plugin-config#the-_extends-key

Similar to https://github.com/release-drafter/release-drafter/issues/1320#issuecomment-1439931634

**Comment by bheemvennapureddy** [comment]
@nvuillam Can you give some insights on this ?

**Comment by nvuillam** [comment]
Yes you can use EXTENDS using a remote .mega-linter.yml :)

for example:

```yaml
# Extend from shared sfdx-hardis Mega-Linter configuration :)
EXTENDS:
  - https://raw.githubusercontent.com/hardisgroupcom/sfdx-hardis/main/config/sfdx-hardis.mega-linter-config.yml

DISABLE_ERRORS_LINTERS:
  - CSS_STYLELINT
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - SALESFORCE_LIGHTNING_FLOW_SCANNER
  - YAML_YAMLLINT
```
