### ISSUE TITLE
ENABLE_ERRORS_LINTERS

### ISSUE THREAD

**Issue by wesley-dean-flexion** [oxsecurity/megalinter#3599]
**Is your feature request related to a problem? Please describe.**

Right now, we have `DISABLE_ERRORS_LINTERS` as a convenient way to provide a list of linters whose findings will not cause MegaLinter to fail a build.

The vision I have is that MegaLinter could run and fail builds if scanners in `REPOSITORY_.*` produce findings but allow MegaLinter to pass builds that have findings in the other linters.

So, the security-centric `REPOSITORY_.*` scanners findings' will be errors while everything else has errors disabled.  It's the inverse of `DISABLE_ERRORS_LINTERS`.

**Describe the solution you'd like**

Example:

```YAML
DISABLE_ERRORS: true
ENABLE_ERRORS_LINTERS:
  - REPOSITORY-SEMGREP
  - REPOSITORY-GITLEAKS
  - [.. rest of the security scanners go here]
```

(the first line may or may not be implied by the presence of `ENABLE_ERRORS_LINTERS`)

**Describe alternatives you've considered**

```YAML
DISABLE_ERRORS: false
DISABLE_ERRORS_LINTERS:
  - MARKDOWN_MARKDOWNLINT
  - MARKDOWN_REMARK_LINT
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - [.. every other linter MegaLinter supports except the security scanners]
```

**Additional context**

This could mirror the behavior of other variables in the [activation / deactivation](https://megalinter.io/latest/config-activation/) functionality, but that may be more involved than would be required at an early stage.

I looked through the [code](https://github.com/oxsecurity/megalinter/blob/main/megalinter/MegaLinter.py#L120-L122) and the issues on GitHub but I didn't see what I was looking for, but that's not to say there isn't a fancy, super-excellent way to get from here to there without changing a line of code.

Just an idea.  Thank you!

**Comment by nvuillam** [comment]
@wesley-dean-flexion good idea :)
If you make a PR allowing that, + update the documentation, I'll gladly accept it :)

**Comment by nvuillam** [comment]
@wesley-dean-flexion like for ENABLE_LINTERS and DISABLE_LINTERS, if ENABLE variable is set, then DISABLE variable is ignored :)

**Comment by wesley-dean-flexion** [comment]
I'll get on it... I swear.......

**Comment by nvuillam** [comment]
@wesley-dean-flexion you do when you can , that's ok :)

Note: next major version should happen in the following weeks :)

**Comment by wesley-dean-flexion** [comment]
@nvuillam Outstanding about the new major version!

**Comment by nvuillam** [comment]
@wesley-dean-flexion in my opinion errors should not be disabled by default, and it's only during the setup and after checking the blocking errors, that someone can decide to consider some linters unrelevant , and individually disable them

But as it seems that your update would not change the current behaviour (that would induce an unwanted breaking change), I'd be ok to validate a PR that "forces enablement of linter errors" if DISABLE_ERRORS is defined to true :)

**Comment by wesley-dean-flexion** [comment]
> errors should not be disabled by default

Agreed.  I generally find acceptable that errors cause a MegaLinter run to fail while warnings do not.  

> would not change the current behavior

Also agreed.  My hope and desire is to not change any existing, default behavior.  The only way this new functionality would happen is when `DISABLE_ERRORS` is set to `True` and individual linters' `_DISABLE_ERRORS` values were explicitly set to `False`.

- `DISABLE_ERRORS` is `False` or undefined (default)
  - `_DISABLE_ERRORS` is `True`: errors from this linter produce zero result (same as now)
  - `_DISABLE_ERRORS` is `False` or undefined: errors from this linter result produce non-zero result (same as now)

- `DISABLE_ERRORS` is `True`
  - `_DISABLE_ERRORS` is `True` or undefined: errors from this linter produce zero result (same as now)
  - **`_DISABLE_ERRORS` is `False: errors from this linter produce non-zero result (THIS IS NEW)**

**Comment by wesley-dean-flexion** [comment]
The goal is still the same as before: I would like to be able to specify a list of linters where errors affirmatively cause MegaLinter to return a non-zero result code while the other linters do not.

It would allow something like this:

```YAML
---

DISABLE_ERRORS: True
REPOSITORY_TRIVY_DISABLE_ERRORS: False
REPOSITORY_GRYPE_DISABLE_ERRORS: False
```

In that situation, errors detected by any linter, scanner, etc. that MegaLinter provides will show up as warnings **except** for Grype and Trivy.  Errors found by those tools will cause MegaLinter to return a non-zero result code.

My vision is that the security-related scanners (so, mostly the `REPOSITORY` descriptor) can cause MegaLinter to serve as a quality gate that would fail a PR-related merge.  If someone wants to put one or two spaces between content and a comment in a YAML file, that shouldn't break a build.  Having someone leave an RDS instance open to `0.0.0.0` should definitely break a build.
