### ISSUE TITLE
lightning-flow-scanner fails for salesforce flavor due to sf cli reporting update availablee

### ISSUE THREAD

**Issue by kmelessanakis** [oxsecurity/megalinter#3761]
lightning-flow-scanner fails due to the sf CLI outputting a new version being available and therefore the following regex failing

```
Unable to extract version with regex re.compile('(?<=lightning-flow-scanner )\\d+(\\.\\d+)+') from  ›   Warning: @salesforce/cli update available from 2.48.6 to 2.49.7.
```

To reproduce just use the SF flavor of megalinter on a salesforce repo

**Comment by nvuillam** [comment]
@kmelessanakis I get the issue

Until we fix it, please can you add the following lines in your .mega-linter.yml ? it should be a working workaround

```yaml
SALESFORCE_LIGHTNING_FLOW_SCANNER_PRE_COMMANDS:
  - command: echo y|sf plugins install lightning-flow-scanner@latest
    cwd: "workspace"
```
