### ISSUE TITLE
New MegaLinter v8 release, with Grafana !

### ISSUE THREAD

**Issue by nvuillam** [oxsecurity/megalinter#3913]
TODO

**Comment by nvuillam** [comment]
I added some debug outputs to help investigate

@practicalli-johnny please could you try with beta version and  `LOG_LEVEL: DEBUG` then share the job execution link ? :)

**Comment by practicalli-johnny** [comment]
Added LOG_LEVEL: DEBUG to the megalinter.yaml file and updated the Megalinter GitHub workflow to use @beta 
```yaml
uses: oxsecurity/megalinter/flavors/java@beta
```

[GitHub actions workflow output](https://github.com/practicalli/megalinter-test/actions/runs/11009524276/job/30569365759): no data in Grafana dashboard.

I will try the main megalinter image rather than the java flavour.

**Comment by nvuillam** [comment]
It should work the same with any flavor :'(

**Comment by nvuillam** [comment]
@practicalli-johnny I don't understand why I can't find any [Reporters] in the log :'(

![image](https://github.com/user-attachments/assets/fce08560-415c-4ed2-9773-ffeb3b22c536)

Please can you try to add the LOG_LEVEL: true directly in the Github workflow variables and not the .mega-linter.yml ?

**Comment by practicalli-johnny** [comment]
Updated LOG_LEVEL to be only in the GitHub Workflow yaml file.

[GitHub Workflow log](https://github.com/practicalli/megalinter-test/actions/runs/11010384364/job/30572182776)

**Comment by practicalli-johnny** [comment]
Megalinter sent logs to Grafana at 9:50 this morning, so when I added `ENABLE_LOGS=true` to the megalinter GitHub workflow yaml file.

![image](https://github.com/user-attachments/assets/01634b9e-eb37-4b29-b680-1b73ad5ba2d7)
 
The dashboards are now working too:

![image](https://github.com/user-attachments/assets/f2b4152d-049e-4bea-bf09-b3f3b73c5f1b)

The home page of Grafana suggests the logs arent working, perhaps its because the number of logs is too low and being rounded down (or they are not looking at the right log source).

Later today I will change back to the java flavour of megalinter and confirm if logs are still being sent.

**Comment by nvuillam** [comment]
@practicalli-johnny great feedback, many thanks :)
If you have ideas of better dashboards than the very simple and ugly ones I created, I'd be delighted to see them ! :)

**Comment by nvuillam** [comment]
![image](https://github.com/user-attachments/assets/7656d053-245c-4093-899e-7710828708e9)

Seing this one I wonder if you didn't select the wrong datasource when matching dashboards & sources at the import

Maybe selected prometheus instead of loki, or the contrary ?
On main dashboard you're supposed to have only one number by linter (the number of errors) , and the elapsed time is available in sub-dashboards after clicking on the button

**Comment by nabondance** [comment]
Hi,
I was about to create an issue of the sending of metrics to Grafana not working on flavors.
Then I found this conversation and tried to solve my issue like you did (by adding `ENABLE_LOGS=true`), but it didn't worked, even on beta flavors.

Tell me if you'd prefer a new specific issue.

My findings so far:
using `oxsecurity/megalinter/flavors/javascript@beta` (or v8):
-->  the workflow doesn't even try to send data
e.g. https://github.com/nabondance/Trailhead-Stats/actions/runs/11042265194/job/30674254975?pr=112

using `oxsecurity/megalinter@v8.0.0`:
--> the workflow send data and the grafana works perfectly
e.g. https://github.com/nabondance/Trailhead-Stats/actions/runs/11041968876/job/30673385205


The grafana log, with the only try without flavors sending data:
<img width="516" alt="image" src="https://github.com/user-attachments/assets/93007e15-44f2-4ede-96a2-55e1279a766e">

The `env` in the MegaLinter step:
```
          API_REPORTER: true
          API_REPORTER_URL: ${{ secrets.API_REPORTER_URL }}
          API_REPORTER_BASIC_AUTH_USERNAME:
            ${{ secrets.API_REPORTER_BASIC_AUTH_USERNAME }}
          API_REPORTER_BASIC_AUTH_PASSWORD:
            ${{ secrets.API_REPORTER_BASIC_AUTH_PASSWORD }}
          API_REPORTER_METRICS_URL: ${{ secrets.API_REPORTER_METRICS_URL }}
          API_REPORTER_METRICS_BASIC_AUTH_USERNAME:
            ${{ secrets.API_REPORTER_METRICS_BASIC_AUTH_USERNAME }}
          API_REPORTER_METRICS_BASIC_AUTH_PASSWORD:
            ${{ secrets.API_REPORTER_METRICS_BASIC_AUTH_PASSWORD }}
          API_REPORTER_DEBUG: true
          ENABLE_LOGS: true
          LOG_LEVEL: DEBUG
```

I really don't understand why it is not working when using a flavor and why the solution you found doesn't work for me.

I'm available if you have questions or need to test more things.

**Comment by nvuillam** [comment]
@nabondance (coucou Nathan je t'ai reconnu 😄 ) > Please can you try with beta version of a flavor ?
There are new logs showing activation / deactivation of Reporters, it should help

**Comment by nabondance** [comment]
(Bravo  ! 😁)

Tried with the step:
```
- name: MegaLinter
        uses: oxsecurity/megalinter/flavors/javascript@beta
        id: ml
        env:
          VALIDATE_ALL_CODEBASE: true

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # Uncomment to use ApiReporter (Grafana)
          API_REPORTER: true
          API_REPORTER_URL: ${{ secrets.API_REPORTER_URL }}
          API_REPORTER_BASIC_AUTH_USERNAME:
            ${{ secrets.API_REPORTER_BASIC_AUTH_USERNAME }}
          API_REPORTER_BASIC_AUTH_PASSWORD:
            ${{ secrets.API_REPORTER_BASIC_AUTH_PASSWORD }}
          API_REPORTER_METRICS_URL: ${{ secrets.API_REPORTER_METRICS_URL }}
          API_REPORTER_METRICS_BASIC_AUTH_USERNAME:
            ${{ secrets.API_REPORTER_METRICS_BASIC_AUTH_USERNAME }}
          API_REPORTER_METRICS_BASIC_AUTH_PASSWORD:
            ${{ secrets.API_REPORTER_METRICS_BASIC_AUTH_PASSWORD }}
          API_REPORTER_DEBUG: true
          ENABLE_LOGS: true
          LOG_LEVEL: DEBUG
```
The log with as much debug as possible:
https://github.com/nabondance/Trailhead-Stats/actions/runs/11042265194/job/30695747348
Still nothing trying to send data to loki/prom, the reporters doesn't start

I understand the goal and how to use the flavors, sadly I don't understand how they are generated, I can't help to find if it is related to the flavors themselves
