### ISSUE TITLE
Support helm lint

### ISSUE THREAD

**Issue by cgetzen** [oxsecurity/megalinter#429]
None of the yaml linters or kubeval support helm

**Comment by nvuillam** [comment]
Do you have a helm linter to propose ?

**Comment by cgetzen** [comment]
https://helm.sh/docs/helm/helm_lint

**Comment by nvuillam** [comment]
I'm not (yet) familiar with helm, please could you provide:
- example calls for helm lint
- a valid helm file
- an invalid helm file

Thanks !

**Comment by ThomasSanson** [comment]
Hello,

I would like to incorporate the "helm lint" feature into megalinter.

@nvuillam Here are some example calls for `helm lint`:

```
# Lint a single chart
helm lint mychart

# Lint all charts in a chart directory
helm lint chartdirectory

# Lint a chart and print the output to a file
helm lint mychart > lint-output.txt
```

A valid Helm chart file might look something like this:

```yaml
apiVersion: v2
name: mychart
version: 1.0.0

# A chart can contain one or more charts
charts:
  # This is the name of the chart
  - name: myapp
    # The chart version
    version: 1.0.0
    # A chart can contain one or more templates
    templates:
      # The name of the template
      - name: deployment.yaml
        # The template content
        content: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: myapp-deployment
          spec:
            replicas: 3
            selector:
              matchLabels:
                app: myapp
            template:
              metadata:
                labels:
                  app: myapp
              spec:
                containers:
                  - name: myapp
                    image: myapp:latest
                    ports:
                      - containerPort: 80

```

An invalid Helm chart file might have a syntax error or be missing required fields, for example:

```yaml
apiVersion: v2
name: mychart

# A chart is missing the 'version' field

# A chart can contain one or more charts
charts:
  # This is the name of the chart
  - name: myapp
    # The chart version
    version: 1.0.0
    # A chart can contain one or more templates
    templates:
      # The name of the template
      - name: deployment.yaml
        # The template content
        content: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: myapp-deployment
          spec:
            replicas: 3
            selector:
              matchLabels:
                app: myapp
            template:
              metadata:
                labels:
                  app: myapp
              spec:
                containers:
                  - name: myapp
                    image: myapp:latest
                    ports:
                      - containerPort: 80

```

I hope this helps! Let me know if you have any other questions.

If you would like, I am willing to try making a pull request to include this new linter.

**Comment by ThomasSanson** [comment]
Hello,

I would like to incorporate the "helm lint" feature into megalinter.

@nvuillam Here are some example calls for `helm lint`:

```
# Lint a single chart
helm lint mychart

# Lint all charts in a chart directory
helm lint chartdirectory

# Lint a chart and print the output to a file
helm lint mychart > lint-output.txt
```

A valid Helm chart file might look something like this:

```yaml
apiVersion: v2
name: mychart
version: 1.0.0

# A chart can contain one or more charts
charts:
  # This is the name of the chart
  - name: myapp
    # The chart version
    version: 1.0.0
    # A chart can contain one or more templates
    templates:
      # The name of the template
      - name: deployment.yaml
        # The template content
        content: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: myapp-deployment
          spec:
            replicas: 3
            selector:
              matchLabels:
                app: myapp
            template:
              metadata:
                labels:
                  app: myapp
              spec:
                containers:
                  - name: myapp
                    image: myapp:latest
                    ports:
                      - containerPort: 80

```

An invalid Helm chart file might have a syntax error or be missing required fields, for example:

```yaml
apiVersion: v2
name: mychart

# A chart is missing the 'version' field

# A chart can contain one or more charts
charts:
  # This is the name of the chart
  - name: myapp
    # The chart version
    version: 1.0.0
    # A chart can contain one or more templates
    templates:
      # The name of the template
      - name: deployment.yaml
        # The template content
        content: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: myapp-deployment
          spec:
            replicas: 3
            selector:
              matchLabels:
                app: myapp
            template:
              metadata:
                labels:
                  app: myapp
              spec:
                containers:
                  - name: myapp
                    image: myapp:latest
                    ports:
                      - containerPort: 80

```

I hope this helps! Let me know if you have any other questions.

If you would like, I am willing to try making a pull request to include this new linter.
