### ISSUE TITLE
How to set up the Auto Fix Via PR GitHub Action

### ISSUE THREAD

**Issue by ScottGibb** [oxsecurity/megalinter#4317]
Hi There,

First off thank you so much to the developers and the community surrounding Super Linter. This is exactly the tool I was looking for. I'm trying to integrate it into my Rust Projects and future Projects. 

# The Goal

The project i'm trying to work with can be found here
https://github.com/dysonltd/tmag5273

Its a cross platform rust library that multiple people will be working on. 

The workflow I thought I could get based on the docs was

- Someone submits a PR 
- The Linting Runs
- a subsequent PR is sent to the existing PR with auto lint fixes

However I cant seem to get it to work correctly. Ive trialed out different configurations in this repo:
https://github.com/ScottGibb/ci_playground/pull/6

# The Problem

I cant get the auto Fix PR to work, I managed to get the commit to branch auto fix to work. However id prefer if I could review the linter changes before it changes the PR branch.

**Comment by nvuillam** [comment]
Did you try with `APPLY_FIXES_MODE: pull_request` ? (must be defined directly in your mega-linter.yml github workflow, not in the .mega-linter.yml config file at the root of the repo

**Comment by ScottGibb** [comment]
I did a couple of combinations throughout yesterday and got a wee bit confused.

Most recently i've done this run which has failed: 
https://github.com/dysonltd/tmag5273/actions/runs/12050883645/job/33600712408?pr=5
The error its now giving me is this
```bash
  Error: When the repository is checked out on a commit instead of a branch, the 'base' input must be supplied.
```

**Comment by ScottGibb** [comment]
I managed to fix the above error and subsequently change the workflow slightly. 


```yml
# MegaLinter GitHub Action configuration file
# More info at https://megalinter.io
---
name: MegaLinter

# Trigger mega-linter at every push. Action will also be visible from
# Pull Requests to main
on:
  # Comment this line to trigger action only on pull-requests
  # (not recommended if you don't pay for GH Actions)
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

# Comment env block if you do not want to apply fixes
env:
  # Apply linter fixes configuration
  #
  # When active, APPLY_FIXES must also be defined as environment variable
  # (in github/workflows/mega-linter.yml or other CI tool)
  APPLY_FIXES: all

  # Decide which event triggers application of fixes in a commit or a PR
  # (pull_request, push, all)
  APPLY_FIXES_EVENT: pull_request

  # If APPLY_FIXES is used, defines if the fixes are directly committed (commit)
  # or posted in a PR (pull_request)
  APPLY_FIXES_MODE: pull_request

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  megalinter:
    name: MegaLinter
    runs-on: ubuntu-latest

    # Give the default GITHUB_TOKEN write permission to commit and push, comment
    # issues, and post new Pull Requests; remove the ones you do not need
    permissions:
      contents: write
      issues: write
      pull-requests: write
      statuses: write

    steps:
      # Git Checkout
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}

          # If you use VALIDATE_ALL_CODEBASE = true, you can remove this line to
          # improve performance
          fetch-depth: 0

      # MegaLinter
      - name: MegaLinter

        # You can override MegaLinter flavor used to have faster performances
        # More info at https://megalinter.io/latest/flavors/
        uses: oxsecurity/megalinter/flavors/rust@v8

        id: ml

        # All available variables are described in documentation
        # https://megalinter.io/latest/config-file/
        env:
          # Validates all source when push on main, else just the git diff with
          # main. Override with true if you always want to lint all sources
          #
          # To validate the entire codebase, set to:
          # VALIDATE_ALL_CODEBASE: true
          #
          # To validate only diff with main, set to:
          # VALIDATE_ALL_CODEBASE: >-
          #   ${{
          #     github.event_name == 'push' &&
          #     github.ref == 'refs/heads/main'
          #   }}
          VALIDATE_ALL_CODEBASE: true

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # Uncomment to use ApiReporter (Grafana)
          # API_REPORTER: true
          # API_REPORTER_URL: ${{ secrets.API_REPORTER_URL }}
          # API_REPORTER_BASIC_AUTH_USERNAME: ${{ secrets.API_REPORTER_BASIC_AUTH_USERNAME }}
          # API_REPORTER_BASIC_AUTH_PASSWORD: ${{ secrets.API_REPORTER_BASIC_AUTH_PASSWORD }}
          # API_REPORTER_METRICS_URL: ${{ secrets.API_REPORTER_METRICS_URL }}
          # API_REPORTER_METRICS_BASIC_AUTH_USERNAME: ${{ secrets.API_REPORTER_METRICS_BASIC_AUTH_USERNAME }}
          # API_REPORTER_METRICS_BASIC_AUTH_PASSWORD: ${{ secrets.API_REPORTER_METRICS_BASIC_AUTH_PASSWORD }}
          # API_REPORTER_DEBUG: false

          # ADD YOUR CUSTOM ENV VARIABLES HERE TO OVERRIDE VALUES OF
          # .mega-linter.yml AT THE ROOT OF YOUR REPOSITORY

      # Upload MegaLinter artifacts
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: MegaLinter reports
          path: |
            megalinter-reports
            mega-linter.log
--------------------------------------------------------------------------------------------------
      # Create pull request if applicable
      # (for now works only on PR from same repository, not from forks)
      - name: Create Pull Request with applied fixes
        uses: peter-evans/create-pull-request@v6
        id: cpr
        if: >-
          steps.ml.outputs.has_updated_sources == 1 &&
          (
            env.APPLY_FIXES_EVENT == 'all' ||
            env.APPLY_FIXES_EVENT == github.event_name
          ) &&
          env.APPLY_FIXES_MODE == 'pull_request' &&
          (
            github.event_name == 'push' ||
            github.event.pull_request.head.repo.full_name == github.repository
          ) &&
          !contains(github.event.head_commit.message, 'skip fix')
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          commit-message: "[MegaLinter] Apply linters automatic fixes"
          title: "[MegaLinter] Apply linters automatic fixes"
          labels: bot
          branch: megalinter-fixes-${{ github.head_ref }}
          body: |
            MegaLinter has automatically applied linters fixes on this PR.
            Please review the changes and merge if they are correct.
          base: ${{ github.head_ref }}

      - name: Post PR Comment
        if: >-
          steps.ml.outputs.has_updated_sources == 1 &&
          (
            env.APPLY_FIXES_EVENT == 'all' ||
            env.APPLY_FIXES_EVENT == github.event_name
          ) &&
          env.APPLY_FIXES_MODE == 'pull_request' &&
          (
            github.event_name == 'push' ||
            github.event.pull_request.head.repo.full_name == github.repository
          ) &&
          !contains(github.event.head_commit.message, 'skip fix')
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            MegaLinter has automatically applied linters fixes on this PR.
            Please review the changes and merge if they are correct.
            PR: ${{ steps.cpr.outputs.pull-request-url }}
          hide_and_recreate: true

      - name: Fail if PR Created
        run: |
          if [ "${{ steps.cpr.outputs.pull-request-url }}" != "" ]; then
            echo "A PR with formatting fixes has been created. Please merge it before proceeding."
            exit 1
          fi
--------------------------------------------------------------------------------------------------

      # Create PR Comment
      # - name: Create PR output
      #   if: >-
      #     steps.ml.outputs.has_updated_sources == 1 &&
      #     (
      #       env.APPLY_FIXES_EVENT == 'all' ||
      #       env.APPLY_FIXES_EVENT == github.event_name
      #     ) &&
      #     env.APPLY_FIXES_MODE == 'pull_request' &&
      #     (
      #       github.event_name == 'push' ||
      #       github.event.pull_request.head.repo.full_name == github.repository
      #     ) &&
      #     !contains(github.event.head_commit.message, 'skip fix')
      #   run: |
      #     echo "PR Number - ${{ steps.cpr.outputs.pull-request-number }}"
      #     echo "PR URL - ${{ steps.cpr.outputs.pull-request-url }}"

      # # Push new commit if applicable
      # # (for now works only on PR from same repository, not from forks)
      # - name: Prepare commit
      #   if: >-
      #     steps.ml.outputs.has_updated_sources == 1 &&
      #     (
      #       env.APPLY_FIXES_EVENT == 'all' ||
      #       env.APPLY_FIXES_EVENT == github.event_name
      #     ) &&
      #     env.APPLY_FIXES_MODE == 'commit' &&
      #     github.ref != 'refs/heads/main' &&
      #     (
      #       github.event_name == 'push' ||
      #       github.event.pull_request.head.repo.full_name == github.repository
      #     ) &&
      #     !contains(github.event.head_commit.message, 'skip fix')
      #   run: sudo chown -Rc $UID .git/

      # - name: Commit and push applied linter fixes
      #   uses: stefanzweifel/git-auto-commit-action@v5
      #   if: >-
      #     steps.ml.outputs.has_updated_sources == 1 &&
      #     (
      #       env.APPLY_FIXES_EVENT == 'all' ||
      #       env.APPLY_FIXES_EVENT == github.event_name
      #     ) &&
      #     env.APPLY_FIXES_MODE == 'commit' &&
      #     github.ref != 'refs/heads/main' &&
      #     (
      #       github.event_name == 'push' ||
      #       github.event.pull_request.head.repo.full_name == github.repository
      #     ) &&
      #     !contains(github.event.head_commit.message, 'skip fix')
      #   with:
      #     branch: >-
      #       ${{
      #         github.event.pull_request.head.ref ||
      #         github.head_ref ||
      #         github.ref
      #       }}
      #     commit_message: "[MegaLinter] Apply linters fixes"
      #     commit_user_name: megalinter-bot
      #     commit_user_email: nicolas.vuillamy@ox.security
```

The new workflow will post a comment on the original PR linking the new fixes PR. The branch that is created is named the same as the working branch using the following configuration  `branch: megalinter-fixes-${{ github.head_ref }}`. Any subsequent runs will force push on to the PR fixes branch and update the original pull request. It will then fail the static analysis workflow indicating that the PR is not merged.
