### ISSUE TITLE
feature request to add dclint (lints docker-compose.yml files)

### ISSUE THREAD

**Issue by wesley-dean-flexion** [oxsecurity/megalinter#4381]
## Is your feature request related to a problem? Please describe.

No, not a problem.  I just found a tool last night that lints Docker compose files and it looks pretty nifty.  Cheers, @zavoloklom!

https://github.com/zavoloklom/docker-compose-linter

## Describe the solution you'd like

Please add dclint to the DOCKER descriptor

## Describe alternatives you've considered

I briefly considered not requesting we add this new linter before opting to share it with the group and let others provide their thoughts.

## Additional context

The tool a Node package that can be installed with `npm install dclint` so I'm hoping we can do something like:

```YAML
- linter_name: "dclint"
  is_formatter: true
  linter_repo: "https://github.com/zavoloklom/docker-compose-linter"
  config_file_name: ".dclintrc"
  cli_lint_mode: "list_of_files"
  cli_lint_fix_args_name: "--fix"
  cli_config_arg_name: "--config"

  examples:
    - "dclint --config .dclintrc ."
    - "dclint path/to/docker-compose.yml"

  install:
    npm:
      - dclint
```

(it would need a few more configuration directives for the `linter_rules.*` stuff, the icon, etc.)

What do you all think?
