### ISSUE TITLE
Handling fixes applied by linting

### ISSUE THREAD

**Issue by cfsb-jrose** [oxsecurity/megalinter#4849]
Hello,

We currently run linting in Jenkins pipelines. When we enable `APPLY_FIXES`, I was wondering if megalinter had configuration that would be able to push commit instead of handling independently (e.g. running git commands in the pipeline)?

**Comment by nvuillam** [comment]
@cfsb-jrose the default Jenkinsfile pipeline doesn't allow that, but I'd be glad to update it if you provide the relevant step :)

Basically, it has to do the same than what is done in the GitHub Action

```yaml
      - name: Prepare commit
        if: env.APPLY_FIXES_IF_COMMIT == 'true'
        run: sudo chown -Rc $UID .git/

      - name: Commit and push applied linter fixes
        uses: stefanzweifel/git-auto-commit-action@v5
        if: env.APPLY_FIXES_IF_COMMIT == 'true'
        with:
          branch: >-
            ${{
              github.event.pull_request.head.ref ||
              github.head_ref ||
              github.ref
            }}
          commit_message: "[MegaLinter] Apply linters fixes"
          commit_user_name: megalinter-bot
          commit_user_email: 129584137+megalinter-bot@users.noreply.github.com
```
