### ISSUE TITLE
Select a flavor using the base action

### ISSUE THREAD

**Issue by yannou38** [oxsecurity/megalinter#4907]
Hello,

For security reasons, my company only allow the action oxsecurity/megalinter (with a specific commit SHA).

I would like to use a flavor for performance reasons, and i wanted to know if there was a way to select it (for example with a "with" statement in the workflow file), as downloading the full docker image take a few minutes each run

**Comment by yannou38** [comment]
Thanks, but that does not answer my query, maybe i was unclear ?

What i mean is that, due to cybersecurity reasons, i can ONLY use
```
- name: MegaLinter
   uses: oxsecurity/megalinter@b48455a119cc28045eee8f1e9d0a542a85e71f4f #v7.5.0
      
```
What i hoped for was a clarification on eventual parameters using with, that would change the docker image downloaded, for example something like this:
```
- name: MegaLinter
   uses: oxsecurity/megalinter@b48455a119cc28045eee8f1e9d0a542a85e71f4f #v7.5.0
   with:
        flavor: "python" 
```
But i believe this is not possible since you have flavors available using various actions paths :/
