### ISSUE TITLE
gitleaks scans the entire repository despite `REPOSITORY_GITLEAKS_PR_COMMITS_SCAN: true`

### ISSUE THREAD

**Issue by vkucera** [oxsecurity/megalinter#4918]
**Describe the bug**

gitleaks scans the entire repository despite `REPOSITORY_GITLEAKS_PR_COMMITS_SCAN: true` and `VALIDATE_ALL_CODEBASE: false`.

**To Reproduce**

- Configure `.github/workflows/mega-linter.yml` with:
  ```yaml
  'on': [pull_request_target]
  jobs:
    megalinter:
      steps:
        - uses: actions/checkout@v4
          with:
            ref: ${{ github.event.pull_request.head.sha }}
            fetch-depth: 0
            persist-credentials: false
        - name: MegaLinter
          ... 
          env:
            VALIDATE_ALL_CODEBASE: false
  ```
- Configure `.mega-linter.yml` with:
  `REPOSITORY_GITLEAKS_PR_COMMITS_SCAN: true`.
- Make a PR on GitHub.

**Expected behavior**

MegaLinter makes gileaks scan only files modified by the PR, as promised at https://megalinter.io/latest/descriptors/repository_gitleaks/

**Context**

The issue seems to occur only for `pull_request_target` events with the command `gitleaks detect` missing the commit SHAs.

- Command on `pull_request`:

  ```bash
  gitleaks detect --redact -c /action/lib/.automation/.gitleaks.toml --verbose --source . --log-opts --no-merges --first-parent <SHA_TARGET>^..<SHA_SOURCE>
  ```
- Command on `pull_request_target`:
  ```bash
  gitleaks detect --redact -c /action/lib/.automation/.gitleaks.toml --verbose --source .
  ```

The issues started appearing after bumping MegaLinter version from v8.3.0 to v8.4.2.
