### ISSUE TITLE
How to use ghcr.io image instead of dockerhub image in github action

### ISSUE THREAD

**Issue by WTPOptAxe** [oxsecurity/megalinter#5050]
I'm trying to switch some GitHub workflows from using the dockerhub image to using ghcr.io. This is ahead of the rate limiting changes on Dockerhub because the image is pulled in the workflow before a `docker login` action is run, so we can't rely on our authenticated user.

I can find the image I think I want at ghcr.io/oxsecurity/megalinter-javascript@v8.5.0 and a docker pull on my local machine works.

However, switching from `uses: oxsecurity/megalinter/flavors/javascript@v8.5.0` to `uses: ghcr.io/oxsecurity/megalinter-javascript:v8.5.0` causes the github workflow to not run with an error of
`the `uses' attribute must be a path, a Docker image, or owner/repo@ref`

What's the correct way to use the ghcr.io images in a github action?

Thanks!

**Comment by WTPOptAxe** [comment]
Doh - it's as simple as prefixing with `docker://`

**Comment by nvuillam** [comment]
@WTPOptAxe can you describe how you did it ?

The Github action has an hardcoded target to docker ^^

https://github.com/oxsecurity/megalinter/blob/main/action.yml

There is a long time i'm considering switching to ghcr images by default, maybe now is the good time

**Comment by WTPOptAxe** [comment]
> [@WTPOptAxe](https://github.com/WTPOptAxe) can you describe how you did it ?

Our action simply changed the `uses` line. This means that instead of using the action, we're just running the image entrypoint. But before and after runs look identitical.

Previously in the workflow, we had
```
- name: MegaLinter
  id: ml
  uses: uses: oxsecurity/megalinter/flavors/javascript@v8.5.0
  env:
    VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }} 
    GITHUB_TOKEN: ${{ secrets.OUR_GH_SECRET_NAME}}
```

Now we have
```
- name: MegaLinter
  id: ml
  uses: docker://ghcr.io/oxsecurity/megalinter-javascript:v8.5.0
  env:
    VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }} 
    GITHUB_TOKEN: ${{ secrets.OUR_GH_SECRET_NAME}}
```
