### ISSUE TITLE
Run Prettier on CSS, GraphQL, HTML, JSX, Markdown, and TSX Files

### ISSUE THREAD

**Issue by Kurt-von-Laven** [oxsecurity/megalinter#782]
**Is your feature request related to a problem? Please describe.**
By default, Mega-Linter only runs Prettier on JavaScript, JSON, TypeScript, and YAML files.

**Describe the solution you'd like**
It would be ideal to run Prettier on all file types that it supports by default. This may lead to the need for more options similar to `DEFAULT_JAVASCRIPT_STYLE` and `DEFAULT_TYPESCRIPT_STYLE` where Prettier conflicts with other linters. It would be ideal to offer a single option (e.g., `ENABLE_PRETTIER`) that sets all appropriate default styles to `"prettier"`.

**Describe alternatives you've considered**
In the meantime, one can either configure Prettier to run on additional extensions or run Prettier separately and disable or compatibly configure any conflicting linters. For the former case, here is an excerpt that can be added to `.mega-linter.yml`:

```yaml
JAVASCRIPT_PRETTIER_FILE_EXTENSIONS:
  - .css
  - .graphql
  - .htm
  - .html
  - .saas
  - .scss
  - .js
  - .jsx
  - .tsx
```

**Additional context**
[Prettier](https://prettier.io/) may add even more languages and formats in the future, and there are already many community plugins for other languages.

**Comment by nvuillam** [comment]
When there are several formatters for a language, Mega-Linter architecture can work only if they are described in the descriptors, so even if it's not nice, your first proposition "DEFAULT_JAVASCRIPT_STYLE and DEFAULT_TYPESCRIPT_STYLE " is what needs to be implemented

Would you like to make a PR ? ^^

**Comment by Kurt-von-Laven** [comment]
This is on my backlog for now since the workaround is straightforward.

**Comment by IlanCosman** [comment]
This should stay open :)

**Comment by nvuillam** [comment]
ok but i hope someone will make the PR, because it's too big for my current bandwith ^^

**Comment by Kurt-von-Laven** [comment]
I wonder if it would be better overall to do this for v6 and remove linters that conflict with Prettier. The obvious drawbacks I see are that this would force users who have been using the conflicting linters to choose between running those linters outside of MegaLinter and disabling Prettier, not upgrading MegaLinter (not advisable for security reasons), and accepting Prettier as the new world order. There are a few benefits I see to this:

- simpler implementations lower maintenance burdens and decrease turnaround times for new features.
- reduced dependency surface area reduces Docker image sizes, runtime, build time, build flakiness, and percentage of maintenance bandwidth dedicated to troubleshooting dependency conflicts and breakages caused by upgrades.
- reduced configuration surface area reduces the time spent adapting MegaLinter per downstream repository (and debating pros and cons of stylistic considerations rather than whatever they would rather be doing) as well as issues first encountered by users since the combinatorial explosion makes testing all combinations of settings impossible.
- anecdotally, Prettier works very well for our projects and many others, fits well with MegaLinter’s goal of supporting a vast array of file types, and espouses a similar low-configuration philosophy. There is now even [a full port for C#](https://github.com/belav/csharpier) that is vastly faster, slimmer, and in my opinion more powerful than dotnet-format!
- MegaLinter never prevents anyone from running any tool they like externally and configuring them however they like, disabling any linters they don’t wish to run, or creating their own plugins.

Curious how others feel about the trade offs here and what I may have missed. I can compile a list of conflicting linters if that would be helpful.

**Comment by liblaf** [comment]
We are able to add support for [Prettier](https://prettier.io) through [Megalinter plugins](https://megalinter.io/latest/plugins/). I created a `MARKDOWN_PRETTIER` Plugin:

<details>

<summary><a href="https://github.com/liblaf/hello-megalinter/blob/main/mega-linter-plugin-prettier/markdown.megalinter-descriptor.yml"><code>mega-linter-plugin-prettier/markdown.megalinter-descriptor.yml</code></a></summary>

```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/megalinter/megalinter/main/megalinter/descriptors/schemas/megalinter-descriptor.jsonschema.json
# https://github.com/oxsecurity/megalinter/blob/7e0440a1550723da68bc2befb8c6bcd71bcb963b/megalinter/descriptors/json.megalinter-descriptor.yml#L168-L223
# https://github.com/oxsecurity/megalinter/blob/main/megalinter/descriptors/markdown.megalinter-descriptor.yml
descriptor_flavors:
  - all_flavors
descriptor_id: MARKDOWN
descriptor_label: Markdown
descriptor_type: format
file_extensions:
  - .md
  - .mdx
linters:
  - can_output_sarif: false
    cli_config_arg_name: --config
    cli_lint_extra_args:
      - --check
    cli_lint_fix_arg_name: --write
    cli_lint_fix_remove_args:
      - --check
    cli_lint_mode: list_of_files
    config_file_name: .prettierrc.json
    examples:
      - "prettier --check myfile.md"
      - "prettier --config .prettierrc.json --check myfile.md"
      - "prettier --config .prettierrc.json --write myfile.md" # format
    ide:
      atom:
        - name: prettier-atom
          url: https://github.com/prettier/prettier-atom
        - name: atom-mprettier
          url: https://github.com/t9md/atom-mprettier
        - name: atom-miniprettier
          url: https://github.com/duailibe/atom-miniprettier
      emacs:
        - name: prettier-emacs
          url: https://github.com/prettier/prettier-emacs
        - name: prettier.el
          url: https://github.com/jscheid/prettier.el
        - name: apheleia
          url: https://github.com/raxod502/apheleia
      idea:
        - name: Prettier
          url: https://plugins.jetbrains.com/plugin/10456-prettier
          id: intellij.prettierJS
      sublime:
        - name: JsPrettier
          url: https://packagecontrol.io/packages/JsPrettier
      vim:
        - name: vim-prettier
          url: https://github.com/prettier/vim-prettier
      visual_studio:
        - name: JavaScriptPrettier
          url: https://github.com/madskristensen/JavaScriptPrettier
      vscode:
        - name: prettier-vscode
          url: https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode
    ignore_file_name: .prettierignore
    ignore_for_flavor_suggestions: true
    install:
      npm:
        - prettier
    is_formatter: true
    linter_banner_image_url: https://todo.com
    linter_icon_png_url: https://prettier.io/icon.png
    linter_image_url: https://prettier.io/icon.png
    linter_name: prettier
    linter_repo: https://github.com/prettier/prettier
    linter_rules_configuration_url: https://prettier.io/docs/en/configuration
    linter_rules_ignore_config_url: https://prettier.io/docs/en/ignore#ignoring-files-prettierignore
    linter_rules_inline_disable_url: https://prettier.io/docs/en/ignore#markdown
    linter_rules_url: https://prettier.io/docs/en/options
    linter_spdx_license: MIT
    linter_url: https://prettier.io
    name: MARKDOWN_PRETTIER
```

</details>

See an example workflow run [here](https://github.com/liblaf/hello-megalinter/actions/runs/12823714218/job/35758684534#step:4:87). The changes made by Prettier can be seen in the [PR](https://github.com/liblaf/hello-megalinter/pull/4/files).
